# This is a basic workflow to help you get started with Actions

name: Account Mapper

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      envType:
        description: "Account Name"
        type: choice
        default: sbx
        options:
         - sbx
         - qa

env:
  sbx: 123456678
  qa: 19921504
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Select Account Number
        id: account-id
        run: |
          envType="${{ inputs.envType }}"
          echo "----->$envType<--------"
          accountId=${{ fromJson('{ sbx: "i386", dev: "x86_64" }')[envType] }}
          echo "******** $accountId ********"
          echo "::set-output name=accountId::$accountId"
          

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          accountId=${{ steps.account-id.outputs.accountId }}
          echo "Selected Account: $accountId"


