# This is a basic workflow to help you get started with Actions

name: Account Mapper

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      envType:
        description: "Account Name"
        type: choice
        default: sbx
        options:
         - sbx
         - qa

env:
  ACCOUNT_ID: |
    sbx: 123456678
    qa: 19921504
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Select Account Number
        id: account-id
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y
          envType="${{ inputs.envType }}"
          accountId="${{ env.ACCOUNT_ID }}"
          echo $envType
          echo "$ACCOUNT_ID" > accounts.yml
          ls
          echo "******* ********"
          echo "******* YAML ********"
          cat accounts.yml
          yq eval '.sbx' accounts.yml
          echo "::set-output name=accountId::$accountId"
          

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: |
#           accountId=${{ steps.account-id.outputs.accountId }}
#           echo "Selected Account: $accountId"


