# This is a basic workflow to help you get started with Actions

name: Simple test GH Actions

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      env:
        required: true
        description: 'Env Type'
        type: choice
        options:
          - npd
          - prd
      instance:
        required: true
        description: 'instance number'
        default: '1'



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: npd

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run Hello World command
        run: |
          echo ${{ inputs.env }}-${{ inputs.instance }}
